Ja minimum version 21 added
Using a Java version below 21 results in Exception in thread "main" java.lang.NoClassDefFoundError: java/util/SequencedCollection.

SequencedCollection is available since Java version 21.